// a4-EllysGorodisch/src/App.svelte
<script>
  const getTodos = function () {
    const p = fetch("/read", {
      method: "GET",
    })
      .then((response) => response.json())
      .then((json) => {
        console.log(json);
        return json;
      });

    return p;
  };

  const addTodo = function (e) {
    const todo = document.querySelector("input").value;
    promise = fetch("/add", {
      method: "POST",
      body: JSON.stringify({ name: todo, completed: false }),
      headers: { "Content-Type": "application/json" },
    }).then((response) => response.json());
  };

  const toggle = function (e) {
    fetch("/change", {
      method: "POST",
      body: JSON.stringify({
        name: e.target.getAttribute("todo"),
        completed: e.target.checked,
      }),
      headers: { "Content-Type": "application/json" },
    });
  };

  let promise = getTodos();
</script>

<input type="text" />
<button on:click={addTodo}>add todo</button>

{#await promise then todos}
  <ul>
    {#each todos as todo}
      <li>
        {todo.name} :
        <input
          type="checkbox"
          todo={todo.name}
          checked={todo.completed}
          on:click={toggle}
        />
      </li>
    {/each}
  </ul>
{/await}

// src/App.jsx
import React, { useState, useEffect } from 'react'

const Todo = props => (
    <li>{props.name} : 
        <input type="checkbox" defaultChecked={props.completed} onChange={ e => props.onclick( props.name, e.target.checked ) }/>
    </li>
)

const App = () => {
    const [todos, setTodos] = useState([ ]) 

    useEffect(()=> {
        fetch( '/read' )
            .then( response => response.json() )
                .then( json => {
                    setTodos( json ) 
                })
    }, [] )

    function toggle( name, completed ) {
        fetch( '/change', {
            method:'POST',
            body: JSON.stringify({ name, completed }),
            headers: { 'Content-Type': 'application/json' }
        })
    }

    function add() {
        const value = document.querySelector('input').value

        fetch( '/add', {
            method:'POST',
            body: JSON.stringify({ name:value, completed:false }),
            headers: { 'Content-Type': 'application/json' }
        })
        .then( response => response.json() )
            .then( json => {
                setTodos( json )
        })
    }
        
    useEffect( ()=> {
        document.title = `${todos.length} todo(s)`
    })

    return (
        <div className="App">
        <input type='text' /><button onClick={ e => add()}>add</button>
        <ul>
            { todos.map( (todo,i) => <Todo key={i} name={todo.name} completed={todo.completed} onclick={ toggle } /> ) }
        </ul> 
        </div>
    )
}



export default App
